import i18next from "i18next";

export const getTextList = () => ({
  loginYourAccount: i18next.t("login_your_account"),
  welcomeTo26Miles: i18next.t("welcome_to_26Miles"),
  emailAddress: i18next.t("email_address"),
  emailAddressPlaceholder: i18next.t("email_address_placeholder"),
  password: i18next.t("Password"),
  passwordPlaceholder: i18next.t("password_placeholder"),
  signIn: i18next.t("sign_in"),
  forgotPassword: i18next.t("forgot_password"),
  dontHaveAnAccount: i18next.t("dont_have_an_account"),
  signUp: i18next.t("sign_up"),
  login: i18next.t("login"),
  loginSuccess: i18next.t("login_successfully"),
  invalidEmail: i18next.t("invalid_email"),
  emailRequired: i18next.t("email_required"),
  passwordRequired: i18next.t("password_required"),
  firstName: i18next.t("first_name"),
  firstNamePlaceholder: i18next.t("first_name_placeholder"),
  lastName: i18next.t("last_name"),
  lastNamePlaceholder: i18next.t("last_name_placeholder"),
  initials: i18next.t("initials"),
  initialsPlaceholder: i18next.t("initials_placeholder"),
  state: i18next.t("state"),
  selectState: i18next.t("select_a_state"),
  searchStates: i18next.t("search_states"),
  phoneNumber: i18next.t("phone_number"),
  phoneNumberPlaceholder: i18next.t("phone_number_placeholder"),
  confirmPassword: i18next.t("confirm_password"),
  termsAndConditions: i18next.t("terms_and_conditions"),
  termsAndConditionsText: i18next.t("terms_and_conditions_text"),
  privacyPolicy: i18next.t("privacy_policy"),
  register: i18next.t("register"),
  alreadyHaveAnAccount: i18next.t("already_have_an_account"),
  and: i18next.t("and"),
  firstNameRequired: i18next.t("first_name_required"),
  stateRequired: i18next.t("state_required"),
  lastNameRequired: i18next.t("last_name_required"),
  initialsRequired: i18next.t("initials_required"),
  initialsMaxLength: i18next.t("initials_max_length"),
  initialsNoSpaces: i18next.t("initials_no_spaces"),
  phoneRequired: i18next.t("phone_required"),
  invalidPhoneNumber: i18next.t("invalid_phone_number"),
  passwordMinLength: i18next.t("password_min_length"),
  passwordNoSpaces: i18next.t("password_no_spaces"),
  passwordsMustMatch: i18next.t("passwords_must_match"),
  confirmPasswordRequired: i18next.t("confirm_password_required"),
  createYourAccount: i18next.t("create_your_account"),
  otpValidation: i18next.t("otp_validation"),
  weHaveSentOtpOnYourEmailAddress: i18next.t("we_have_sent_otp_on_your_email_address"),
  continue: i18next.t("continue"),
  didntReceiveAnOtp: i18next.t("didnt_receive_an_otp"),
  resendOtp: i18next.t("resend_otp"),
  resendIn: i18next.t("resend_in"),
  resending: i18next.t("resending"),
  appname: i18next.t("26Miles"),
  hello: i18next.t("hello"),
  myWinnings: i18next.t("my_winnings"),
  noWinningsFound: i18next.t("no_winnings_found"),
  vehicleLicensePlate: i18next.t("vehicle.licensePlate"),
  vehicleColor: i18next.t("vehicle.vehicleColor"),
  vehicleMake: i18next.t("vehicle.vehicleMake"),
  vehicleState: i18next.t("vehicle.state"),
  matchAndWin: i18next.t("match_and_win"),
  monthlyAmazingRewards: i18next.t("monthly_amazing_rewards"),
  enterYourInitialsFindAPlateAndWin: i18next.t("enter_your_initials_find_a_plate_and_win"),
  tryNow: i18next.t("try_now"),
  offerClosed: i18next.t("offer_closed"),
  forgotPasswordHeading: i18next.t("forgot_password_heading"),
  sendResetOtp: i18next.t("send_reset_otp"),
  sendOtpEmailDescription: i18next.t("send_Otp_email_description"),
  resetPassword: i18next.t("reset_password"),
  resetPasswordDescription: i18next.t("reset_password_description"),
  resetPasswordButton: i18next.t("reset_password_button"),
  enterNewPassword: i18next.t("enter_new_password"),
  confirmNewPassword: i18next.t("confirm_new_password"),
  profileAndSettings: i18next.t("profile_and_settings"),
  otherSettings:i18next.t('other_settings'),
  manageSubsciption:i18next.t('manage_subscription'),
  languages:i18next.t('languages'),
  deleteAccount:i18next.t('delete_account'),
  darkMode:i18next.t("dark_mode"),
  logout:i18next.t("logout"),
  deleteAccountSuccessMessage:i18next.t("delete_account_success_message"),
  updateProfile:i18next.t("update_profile"),
  done:i18next.t("done"),
  cancel:i18next.t("cancel"),
  selectOption:i18next.t("select_an_option"),
  search:i18next.t("search"),
  licensePlatePlaceHolder:i18next.t("licensePlatePlaceHolder"),
  VehicleColorPlaceHolder:i18next.t("VehicleColorPlaceHolder"),
  VehicleMakePlaceHolder:i18next.t("VehicleMakePlaceHolder"),
  licensePlateRequired:i18next.t("license_plate_required"),
  vehicleMakeRequired:i18next.t("vehicle_make_required"),
  vehicleColorRequired:i18next.t("vehicle_color_required"),
  RegisterAndWin:i18next.t("Register&Win"),
  selectYourDreamGift:i18next.t("select_your_dream_gift"),
  giftSubtitle:i18next.t("giftSubtitle"),
  readyToSubmit:i18next.t("readyToSubmit"),
  submitDetails:i18next.t("submitDetails"),
  submit:i18next.t("vehicle.submit"),
  subcriptionHeading:i18next.t("subcriptionHeading"),
  subscriptionBasicHeading:i18next.t("subscriptionBasicHeading"),
  subscriptionBasicDetail:i18next.t("subscriptionBasicDetail"),
  subscriptionPremiumHeading:i18next.t("subscriptionPremiumHeading"),
  subscriptionPremiumDetail:i18next.t("subscriptionPremiumDetail"),
  monthlyAccess:i18next.t("monthlyAccess"),
  monthlyAccessDescription:i18next.t("monthlyAccessDescription"),
  termsofuse:i18next.t("terms_of_use"),
  mostpopular:i18next.t("most_popular"),
  permonth:i18next.t("per_month"),
  somethingWentWrong: i18next.t('something_went_wrong'),
  message:  i18next.t("message"),
  error:  i18next.t("Error"),
  ok:  i18next.t("ok"),
  success:  i18next.t("success"),
  take_photo:  i18next.t("take_photo"),
  choose_from_library:  i18next.t("choose_from_library"),
  permission_required:  i18next.t("permission_required"),
  library_permission_detail:  i18next.t("library_permission_detail"),
  camera_permission_detail:  i18next.t("camera_permission_detail"),
  failed_to_open_image_library:  i18next.t("failed_to_open_image_library"),
  failed_to_open_camera:  i18next.t("failed_to_open_camera"),
  edit_profile:  i18next.t("edit_profile"),
  retry:  i18next.t("retry"),
  no_internet_connection:  i18next.t("no_internet_connection"),
  it_looks_like_you_are_offline:  i18next.t("it_looks_like_you_are_offline"),
  session_expired:  i18next.t("session_expired"),
  addProfilePhoto:  i18next.t("add_profile_photo"),
  subcription_plans:  i18next.t("subcription_plans"),
  manageSubscriptions_title:  i18next.t("manageSubscriptions_title"),
  manageSubscriptions_currentPlanLabel:  i18next.t("manageSubscriptions_currentPlanLabel"),
  manageSubscriptions_priceSuffix:  i18next.t("manageSubscriptions_priceSuffix"),
  manageSubscriptions_Premium:  i18next.t("manageSubscriptions_Premium"),
  manageSubscriptions_Basic:  i18next.t("manageSubscriptions_Basic"),
  manageSubscriptions_nextBillingDate:  i18next.t("manageSubscriptions_nextBillingDate"),
  manageSubscriptions_cancelSubscription:  i18next.t("manageSubscriptions_cancelSubscription"),
  manageSubscriptions_benefit_ultimateAccess:  i18next.t("manageSubscriptions_benefit_ultimateAccess"),
  manageSubscriptions_benefit_basicDetail:  i18next.t("manageSubscriptions_benefit_basicDetail"),
  manageSubscriptions_benefit_premiumDetail:  i18next.t("manageSubscriptions_benefit_premiumDetail"),
  manageSubscriptions_benefit_exclusiveContent:  i18next.t("manageSubscriptions_benefit_exclusiveContent"),
  manageSubscriptions_subscribeLabel:  i18next.t("manageSubscriptions_subscribeLabel"),
  manageSubscriptions_downgrade:  i18next.t("manageSubscriptions_downgrade"),
  manageSubscriptions_upgrade:  i18next.t("manageSubscriptions_upgrade"),
  manageSubscriptions_disclaimer_line1:  i18next.t("manageSubscriptions_disclaimer_line1"),
  manageSubscriptions_disclaimer_line2:  i18next.t("manageSubscriptions_disclaimer_line2"),
  type_here:  i18next.t("type_here"),
  no_options_found:  i18next.t("no_options_found"),
  congratulations:  i18next.t("congratulations"),
  manageSubscriptionPlatformIOSError:  i18next.t("manageSubscriptionPlatformIOSError"),
  manageSubscriptionPlatformAndroidError:  i18next.t("manageSubscriptionPlatformAndroidError"),
  back_to_login:  i18next.t("back_to_login"),
  subcriptionAlreadyRunningOnIOS:  i18next.t("subcriptionAlreadyRunningOnIOS"),
  subscriptionAlreadyRunningOnAndroid:  i18next.t("subscriptionAlreadyRunningOnAndroid"),
  subscriptionSuccessMessage:  i18next.t("subscriptionSuccessMessage"),
  licensePlateInvalid:  i18next.t("licensePlateInvalid"),
  licensePlateNumberLabel:  i18next.t("licensePlateNumberLabel"),
  address:  i18next.t("address"),
  address_placeholder:  i18next.t("address_placeholder"),
  address_required:  i18next.t("address_required"),
  no_date:  i18next.t("no_date"),
  subscriptionErrorMessage:  i18next.t("subscriptionErrorMessage"),
  submitting:  i18next.t("submitting"),
  update_available:  i18next.t("update_available"),
  update_available_description:  i18next.t("update_available_description"),
  update_now:  i18next.t("update_now"),
  no_matching_addresses_found:  i18next.t("no_matching_addresses_found"),
  




  

  
  

  

  
  
});
